### ISSUE TITLE
Incomplete -V compiler option in vendor package while building for QNX

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/yaml_cpp_vendor#12]
Incomplete -V compiler option in vendor package while building for QNX

**Comment by dirk-thomas** [comment]
@asobhy-qnx With #13 closed is there still something needed in this package to support building for QNX?

**Comment by asobhy-qnx** [comment]
No, fixed by changing toolchain file, see https://github.com/ros2/yaml_cpp_vendor/pull/13
