### ISSUE TITLE
Check for installation before building for dashing and foxy

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/yaml_cpp_vendor#18]
can we add a check if yaml-cpp is already installed on host for dashing and foxy similar to rolling in the CMakeLists.txt file?
The check does not try to build if the yaml-cpp is found. This is being done in rolling ditro but not in foxy and dashing

Basically back port rolling to dashing and foxy distros

@dirk-thomas can this be added to the list of patch release for dashing and foxy

**Comment by dirk-thomas** [comment]
> can we add a check if yaml-cpp is already installed on host for dashing and foxy similar to rolling in the CMakeLists.txt file?
The check does not try to build if the yaml-cpp is found.

I assume you are referring to #16?

> Basically back port rolling to dashing and foxy distros

I have added that PR to the project boards for backporting.
