### ISSUE TITLE
Undefined symbol in rosbag2_storage due to wrong version on yaml-cpp for MacOS Catalina.

### ISSUE THREAD

**Issue by olivier-stasse** [ros2/yaml_cpp_vendor#19]
I run into issue https://github.com/ros2/rosbag2/issues/298 and had to modify the CMakeLists.txt file to install yaml-cpp version 0.6.3

This was necessary to compile ros2 on a Mac Catalina 10.15.7

Making the modification proposed by @tanzby fixed the matter.

But will it not be possible to fix the matter for macOS and all by updating the version in this repository ?

**Comment by clalancette** [comment]
> But will it not be possible to fix the matter for macOS and all by updating the version in this repository ?

That is a good idea, yes.  Would you be interested in making the change, testing it out locally, and proposing a PR to do that?

**Comment by olivier-stasse** [comment]
> > But will it not be possible to fix the matter for macOS and all by updating the version in this repository ?
> 
> That is a good idea, yes. Would you be interested in making the change, testing it out locally, and proposing a PR to do that?

Dear @clalancette,
Thanks for the feedback. Please find the following pull request https://github.com/ros2/yaml_cpp_vendor/pull/20

**Comment by clalancette** [comment]
This should have been fixed by https://github.com/ros2/yaml_cpp_vendor/pull/25 , so closing this out.  Feel free to reopen if you are still having problems.
