### ISSUE TITLE
Should this be added to rosdep?

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/yaml_cpp_vendor#2]
I noticed there's still an `rviz_yaml_cpp_vendor` key associated with rviz2, but that repo no longer contains it.

**Comment by mjcarroll** [comment]
I'm a little unclear on what's going on here, it's not in the `master` branch of https://github.com/ros2/rviz 

It has also been added to the `ros2.repos` file here: https://github.com/ros2/ros2/pull/585

We haven't cut a release (it will be for crystal), so it won't appear in any distribution.yaml files yet.

**Comment by SteveMacenski** [comment]
rosdistro (https://github.com/ros2/rosdistro/blob/ros2/bouncy/distribution.yaml#L1230) shows the `rviz_yaml_cpp_vendor` package in its metapackage in that index, but it doesnt appear in the master branch in rviz2 as you point out.

Got it - targeting crystal. Thanks!
