### ISSUE TITLE
Problem with jazzy

### ISSUE THREAD

**Issue by yguel** [ros2/yaml_cpp_vendor#51]
Hi,
I am the maintainer of the ros package ethercat_driver_ros2 (https://github.com/ICube-Robotics/ethercat_driver_ros2) in which we use yaml-cpp to parse configuration files.
We support only ROS2 LTS.
On humble we used the yaml_cpp_vendor like that:
As a dependency in our packages (https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/humble/ethercat_generic_plugins/ethercat_generic_slave/package.xml):
``` xml
<depend>yaml_cpp_vendor</depend>
```

And in the CMakeLists.txt (https://github.com/ICube-Robotics/ethercat_driver_ros2/blob/humble/ethercat_generic_plugins/ethercat_generic_slave/CMakeLists.txt)
```CMake
...
find_package(yaml_cpp_vendor REQUIRED)
...
ament_target_dependencies(
  ethercat_generic_slave
  ethercat_interface
  pluginlib
  yaml_cpp_vendor
)
```
Now, in jazzy, with the updated yaml_cpp_vendor package, we have linking problems as if the library was not added to the link dependencies.
Indeed if I add manually yaml-cpp in the target_link_libraries, the linking problem disappears.
Replace : 
``` CMake
target_link_libraries(test_generic_ec_slave
    ethercat_generic_slave
  )
```
by:
``` CMake
target_link_libraries(test_generic_ec_slave
    ethercat_generic_slave
    yaml-cpp
  )
```
It does not sound user friendly and I wonder if this is the new expected usage especially with respect to the yaml-cpp library version.
Furthermore, this is not clear for me how the dependency on this library should be managed in jazzy, I like the fact that the library is declared as a dependency with ament_target_dependencies and in the <depend> tag of the package and that everything is managed by colcon for the users afterwards.

In terms of library version, I would like to have your feedback concerning potential portage problems.
Humble version (0.7.0) works for our package but we did not test nor have any idea of the work to do to switch to 0.8.0 (but considering semver meaning, it should be 100% compatible and hence, it should not be one of our concerns).

Your inputs will be greatly appreciated.

**Comment by clalancette** [comment]
> It does not sound user friendly and I wonder if this is the new expected usage especially with respect to the yaml-cpp library version.

Yes, this is the new expected usage.  In point of fact, we actually recommend:

```
target_link_libraries(mylib yaml-cpp::yaml-cpp)
```

> Furthermore, this is not clear for me how the dependency on this library should be managed in jazzy, I like the fact that the library is declared as a dependency with ament_target_dependencies and in the tag of the package and that everything is managed by colcon for the users afterwards.

It should all still be managed by colcon.  It is true that it will not work exactly the same with `ament_target_dependencies` now; we haven't noticed that because we switched the ROS 2 core away from `ament_target_dependencies`, in favor of using `target_link_libraries` everywhere.  That may be the way forward here for you as well.

**Comment by yguel** [comment]
Thank you very much for your answer.
I will have a look at this move, away from ament_target_dependencies.

**Comment by yguel** [comment]
I tried to add yaml-cpp::yaml-cpp in the target_link_libraries but I got the following error message
``` bash
CMake Error at CMakeLists.txt:68 (target_link_libraries):
  Target "test_ec_pdo_channel_manager" links to:

    yaml-cpp::yaml-cpp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

But if I put yaml-cpp instead, I do not have any error message.

**Comment by clalancette** [comment]
> But if I put yaml-cpp instead, I do not have any error message.

You also need to do `find_package(yaml-cpp REQUIRED)` earlier in the CMakeLists.txt.  See https://github.com/ros-perception/image_common/blob/rolling/camera_calibration_parsers/CMakeLists.txt for an example of where we use this in the core.

**Comment by yguel** [comment]
ament_target_dependencies does a lot of good stuff like handling include directories, target_link_libraries and so on, which was very convenient.

I am looking at guidelines or explanations to move away from ament_target_dependencies (especially with a function providing me the same kind of syntactic sugar), but do not find one.
Have you some pointer to share ?

**Comment by clalancette** [comment]
> I am looking at guidelines or explanations to move away from ament_target_dependencies (especially with a function providing me the same kind of syntactic sugar), but do not find one.
> Have you some pointer to share ?

No, we don't have any official guidance on this yet, mostly because there is one minor bug with it that we haven't solved yet.

The basic reason to move away from `ament_target_dependencies` is that it duplicates functionality that CMake has builtin (namely, `target_link_libraries`).  It was developed in the days before `target_link_libraries` was really available, which is why we have it, but now that CMake has a superset of the functionality, there is less need for it.

**Comment by yguel** [comment]
I understood that it was very different: 
for me, target_link_library was only adding libraries (linker data)
whereas
ament_target_dependencies looks at packages and under the hood, it declares the necessary linkages and directory includes (compiler data) that the packages in the dependencies export.
If I had to replace ament_target_dependencies, I would have to use target_include_directories and target_link_libraries for all packages.
This looks like a regression in terms of functionalities for the developers.

Side note:
The jazzy documentation should be modified asap, since it recommends using ament_target_dependencies (https://docs.ros.org/en/jazzy/How-To-Guides/Ament-CMake-Documentation.html).

**Comment by clalancette** [comment]
> The jazzy documentation should be modified asap, since it recommends using ament_target_dependencies (https://docs.ros.org/en/jazzy/How-To-Guides/Ament-CMake-Documentation.html).

No, like I said, we aren't officially recommending this yet.  Once we do start recommending this, we'll update the documentation.

**Comment by yguel** [comment]
For the moment, my attempts to upgrade using yaml-cpp::yaml-cpp and removing ament_target_dependencies fail miserably. 
Maybe I am hitting the little bug you mentioned.
As my first solution was working, I will wait for the guidelines to be published before investing more time.

**Comment by clalancette** [comment]
> For the moment, my attempts to upgrade using yaml-cpp::yaml-cpp and removing ament_target_dependencies fail miserably.
> Maybe I am hitting the little bug you mentioned.

No, you shouldn't be.  The bug has to do with message packages.  Can you show me the CMakeLists.txt that is failing for you?

**Comment by sloretz** [comment]
> ament_target_dependencies looks at packages and under the hood, it declares the necessary linkages and directory includes (compiler data) that the packages in the dependencies export.
If I had to replace ament_target_dependencies, I would have to use target_include_directories and target_link_libraries for all packages.

With modern CMake targets, `target_link_libraries()` handles include directories, compiler options, compile definitions, etc. `target_link_libraries()` works on a per-target basis while `ament_target_dependencies()` works on a per-package basis. This means with `target_link_libraries()` your targets only depend on the targets they need, which can speed up your builds.

**Comment by yguel** [comment]
Thank you for your proposition: 
There are 2 branches on the following repository: https://github.com/yguel/ethercat_driver_ros2.git
jazzy
yguel-jazzy-remove-ament-target-dependencies

- jazzy compiles fine with the changes I made
- yguel-jazzy-remove-ament-target-dependencies fails
It does not find the includes of one of the libraries of a subfolder from another one:
``` bash
Starting >>> ethercat_msgs
Finished <<< ethercat_msgs [0.98s]                                                                   
Starting >>> ethercat_manager
Finished <<< ethercat_manager [0.29s]                                                                       
Finished <<< ethercat_interface [1.50s]                  
Starting >>> ethercat_driver
Starting >>> ethercat_generic_slave
--- stderr: ethercat_generic_slave                                                                            
In file included from /home/ubuntu/ros2_ws/src/ethercat_driver_ros2/ethercat_generic_plugins/ethercat_generic_slave/src/generic_ec_slave.cpp:19:
/home/ubuntu/ros2_ws/src/ethercat_driver_ros2/ethercat_generic_plugins/ethercat_generic_slave/include/ethercat_generic_plugins/generic_ec_slave.hpp:25:10: fatal error: ethercat_interface/ec_slave.hpp: No such file or directory
   25 | #include "ethercat_interface/ec_slave.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

To compile I build a docker image with the dependencies of the ethercat_driver_ros2, the Dockerfile is there: https://github.com/yguel/ethercat_driver_ros2/blob/jazzy/.docker/Dockerfile

To start the container I do the following

``` bash
mkdir -p ros2_jazzy/src
cd ros2_jazzy/src && git clone https://github.com/yguel/ethercat_driver_ros2.git
git checkout yguel-jazzy-remove-ament-target-dependencies
cd ../..
docker run -v $PWD:/home/ubuntu/ros2_ws -it ros2_ethercat:jazzy /bin/bash
```

From the container (or from a vscode session attached to the container) it is possible to build the project as usual, the ros2 workspace is in /home/ubuntu/ros2_ws in the container filesystem.

By changing the branch from :
``` bash
git checkout yguel-jazzy-remove-ament-target-dependencies
```
to

```bash
git checkout jazzy
```
You can see the changes that I made that allow the project to compile.

Thanks a lot for your help.

I have quite some work to make functional checks, since ros2 control evolved a lot from humble to jazzy. I will focus on those checks now.

**Comment by yguel** [comment]
I got error at plugin loading with the yaml-cpp library, it cannot find symbols from the library:
```bash
Actual: it throws pluginlib::LibraryLoadException with description "Failed to load library /home/ubuntu/ros2_ws/install/ethercat_generic_slave/lib/libethercat_generic_slave.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library dlopen error: /home/ubuntu/ros2_ws/install/ethercat_generic_slave/lib/libethercat_generic_slave.so: undefined symbol: _ZTIN4YAML13BadConversionE, at ./src/shared_library.c:99".
```
_ZTIN4YAML13BadConversionE is a symbol from the YAML-cpp library corresponding to BadConversion exception.

**Comment by yguel** [comment]
I solved all the problems by adding yaml-cpp in a target_link_libraries command with the libraries as target instead of the test binaries.

```CMake
target_link_libraries(${PROJECT_NAME} yaml-cpp)
```

**Comment by wjwwood** [comment]
Based on our "waffle" issue triage meeting, closing this.
